import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/doctor_profile_model.dart';
import '../models/modification_log.dart';

class PdfReportService {
  Future<Uint8List> generateReport({
    required DoctorProfileModel doctor,
    required String transcribedText,
    required String patientName,
    required String patientAge,
    List<ModificationLog>? modificationHistory,
  }) async {
    final doc = pw.Document();
    final now = DateTime.now();
    final dateFormatter = DateFormat('MMMM d, yyyy');
    final timeFormatter = DateFormat('h:mm a');

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Medical Report',
                        style: pw.TextStyle(
                            fontSize: 24, fontWeight: pw.FontWeight.bold)),
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.end,
                      children: [
                        pw.Text(dateFormatter.format(now)),
                        pw.Text(timeFormatter.format(now)),
                      ],
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),

              // Doctor & Hospital Info
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey),
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text('Doctor: ${doctor.name}',
                            style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                        pw.Text('Speciality: ${doctor.speciality}'),
                        if (doctor.clinicAddress.isNotEmpty)
                          pw.Text('Hospital/Clinic: ${doctor.clinicAddress}'),
                      ],
                    ),
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text('Patient Name: $patientName',
                            style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                        pw.Text('Patient Age: $patientAge'),
                      ],
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 30),

              // Report Content
              pw.Text('Transcription / Report:',
                  style: pw.TextStyle(
                      fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey100,
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                ),
                child: pw.Text(transcribedText),
              ),
              
              pw.Spacer(),

              // Modification History
              if (modificationHistory != null && modificationHistory.isNotEmpty) ...[
                 pw.Text('Modification History:',
                    style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                 pw.SizedBox(height: 5),
                 ...modificationHistory.map((log) => pw.Text(
                   '${log.timestamp.toString().substring(0, 19)} - ${log.action}',
                   style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
                 )),
                 pw.SizedBox(height: 20),
              ],
              
              // Footer
              pw.Divider(),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Generated by AI Gris',
                      style: const pw.TextStyle(
                          fontSize: 10, color: PdfColors.grey700)),
                  pw.Text('Confidential',
                      style: const pw.TextStyle(
                          fontSize: 10, color: PdfColors.red)),
                ],
              ),
            ],
          );
        },
      ),
    );

    return await doc.save();
  }

  Future<void> saveAndLaunchReport(Uint8List bytes, String fileName) async {
    await Printing.sharePdf(bytes: bytes, filename: fileName);
  }
}
